# Generated by Django 5.2.5 on 2025-08-16 18:37

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B3TransactionReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(storage=django.core.files.storage.FileSystemStorage(allow_overwrite=True), upload_to='reports/B3/transactions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('report',), name='unique_b3_transaction_report')],
            },
        ),
    ]
