# Generated by Django 5.2.5 on 2025-08-14 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='UNKNOWN', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='UNKNOWN', max_length=10)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('classification', models.ForeignKey(default='UNKNOWN', on_delete=django.db.models.deletion.SET_DEFAULT, to='transactions.assetclassification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionInstitutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UNKNOWN', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Unknown', 'UNKNOWN_OPERATION')])),
                ('operation_date', models.DateField(blank=True, null=True)),
                ('settlement_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.assetidentification')),
                ('institution_name', models.ForeignKey(default='UNKNOWN', on_delete=django.db.models.deletion.SET_DEFAULT, to='transactions.transactioninstitutions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='assetclassification',
            constraint=models.UniqueConstraint(fields=('user', 'type'), name='unique_asset_classification'),
        ),
        migrations.AddConstraint(
            model_name='assetidentification',
            constraint=models.UniqueConstraint(fields=('user', 'ticker'), name='unique_asset_identification'),
        ),
        migrations.AddConstraint(
            model_name='transactioninstitutions',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_transaction_institution'),
        ),
    ]
