# Generated by Django 5.2.5 on 2025-08-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('movement_type', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('institution', models.CharField(max_length=100)),
                ('trading_code', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
