# Generated by Django 5.2.5 on 2025-08-10 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='movement_type',
            new_name='operation',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='trading_code',
            new_name='ticker',
        ),
    ]
