# Generated by Django 5.2.5 on 2025-08-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_movement_type_transaction_operation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='TradeOperation',
        ),
    ]
