# Generated by Django 5.2.5 on 2025-08-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_transaction_tradeoperation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeoperation',
            name='id',
        ),
        migrations.AddField(
            model_name='tradeoperation',
            name='pk',
            field=models.CompositePrimaryKey('trade_date', 'operation', 'market', 'institution', 'ticker', 'quantity', 'price', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
