# Generated by Django 5.2.5 on 2025-08-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_tradeoperation_id_tradeoperation_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOperations',
            fields=[
                ('pk', models.CompositePrimaryKey('trade_date', 'operation', 'market', 'institution', 'ticker', 'quantity', 'price', blank=True, editable=False, primary_key=True, serialize=False)),
                ('trade_date', models.DateField()),
                ('operation', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('institution', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='TradeOperation',
        ),
    ]
