# Generated by Django 5.2.5 on 2025-08-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_tradeoperations_delete_tradeoperation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradeoperations',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='tradeoperations',
            name='pk',
            field=models.CompositePrimaryKey('trade_date', 'operation', 'market', 'institution', 'ticker', 'amount', 'price', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
