# Generated by Django 5.2.5 on 2025-08-12 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_rename_quantity_tradeoperations_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClassification',
            fields=[
                ('asset_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AssetIdentification',
            fields=[
                ('asset_ticker', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(blank=True, max_length=100)),
                ('asset_classificatoin', models.ForeignKey(default='UNKNOWN', on_delete=django.db.models.deletion.SET_DEFAULT, to='transactions.assetclassification')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionInstitutions',
            fields=[
                ('institution_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.IntegerField(choices=[(1, 'Buy'), (2, 'Sell'), (3, 'UNKNOWN_OPERATION')])),
                ('operation_date', models.DateField(blank=True, null=True)),
                ('settlement_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.assetidentification')),
                ('institution_name', models.ForeignKey(default='UNKNOWN', on_delete=django.db.models.deletion.SET_DEFAULT, to='transactions.transactioninstitutions')),
            ],
        ),
        migrations.DeleteModel(
            name='TradeOperations',
        ),
    ]
