# Generated by Django 5.2.5 on 2025-08-12 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_assetclassification_assetidentification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetidentification',
            old_name='asset_classificatoin',
            new_name='asset_classification',
        ),
    ]
