# Generated by Django 5.2.5 on 2025-08-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_rename_asset_classificatoin_assetidentification_asset_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionoperations',
            name='operation',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Unknown', 'UNKNOWN_OPERATION')]),
        ),
    ]
