name: Python Django Unit Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.7
        
    - name: Install dependencies
      run: |
        sudo locale-gen pt_BR.UTF-8
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare environment
      run: |
        mkdir -p logs
        sudo update-locale

    - name: Run Python Unittests
      run: |
        python manage.py test
